export const loren = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quam ligula, semper non tristique eu, vulputate non lectus. Quisque faucibus facilisis enim et aliquet. In cursus tincidunt elementum. Vivamus est odio, posuere eu lacinia quis, interdum nec erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vel euismod nisi, nec euismod mi. Donec sagittis eros quis iaculis facilisis. Quisque pharetra dui vitae dui pharetra, vitae tincidunt elit sollicitudin. Praesent id semper sapien.

Donec hendrerit orci vitae leo efficitur, id faucibus tellus aliquam. Curabitur posuere lacus eu enim feugiat dapibus vitae vitae ex. Suspendisse quis lorem sed purus fermentum volutpat. Aliquam pharetra enim eget dignissim eleifend. Nam efficitur tortor eget volutpat rutrum. Curabitur sit amet urna sit amet velit sodales tincidunt. Aliquam laoreet orci sit amet leo luctus, quis facilisis velit porta. Cras finibus eget purus sed tristique. Nulla rhoncus porta tincidunt. Proin congue augue dolor, nec vehicula justo ultricies et. Curabitur venenatis felis augue, vel maximus lorem pharetra convallis. Duis varius urna ligula, ut tristique ligula pretium a.

Duis eu magna ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas a nisi tincidunt, sodales risus in, efficitur nunc. Praesent eget efficitur nulla. Integer gravida eros quis eleifend facilisis. In hac habitasse platea dictumst. Phasellus sed enim fermentum, venenatis nisl eleifend, volutpat quam. Phasellus sit amet enim aliquam nisi dignissim sodales sed nec neque. Sed vitae odio urna. Donec accumsan consequat elit, ac interdum lorem venenatis fringilla. In in laoreet nisl, eget consequat justo. Cras nisl libero, feugiat sed velit tristique, lacinia consequat justo. Donec sagittis odio metus, ac facilisis sem mattis nec. Vestibulum quis congue purus. Nunc elementum orci ut ornare pellentesque.

Aliquam eu nisl condimentum orci dictum aliquet. Nulla facilisi. Nunc dapibus eget nunc eu auctor. Ut non turpis mollis, tempus quam nec, accumsan leo. Mauris feugiat neque lorem, ut volutpat purus facilisis id. Donec eu pellentesque urna. Nam eget euismod mauris. Vestibulum sed dictum lacus, ac interdum odio. Vivamus efficitur lectus a lorem feugiat euismod. Integer ultricies elit ac commodo semper. Nullam eleifend metus nulla, nec pharetra velit finibus ac.

Mauris nisi odio, blandit vel sollicitudin vitae, auctor a nulla. Integer quam ex, dictum quis nibh in, feugiat finibus nisi. Integer mollis nunc eget diam elementum, eget vulputate magna vestibulum. Donec sed pretium justo. Vestibulum vel lacinia erat. Sed ornare mi lacus, vitae dignissim turpis consequat ac. Nulla commodo est non vestibulum semper. Nam blandit dignissim mi id scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean hendrerit augue quis ipsum tempor, at auctor lorem tempus. Aliquam erat volutpat. Donec ultricies tellus ac massa viverra tempus. Phasellus gravida augue eu metus eleifend faucibus.

Sed ac diam orci. Quisque vehicula posuere felis quis rhoncus. In ultrices pellentesque sollicitudin. Ut turpis felis, condimentum eget erat in, feugiat vulputate enim. Curabitur iaculis purus ante, ut tincidunt arcu congue quis. Aliquam pharetra sapien id nisl mollis, id vestibulum neque condimentum. Ut eget sodales orci. Ut massa felis, tempus id finibus non, congue ut odio. Nullam et sollicitudin dolor.

Nam id dignissim turpis. Morbi nec elit at arcu elementum maximus. Aenean sagittis lobortis ligula ac ullamcorper. Nunc et lacus diam. Proin accumsan urna eget nulla scelerisque, sed imperdiet metus volutpat. Quisque eget nulla vitae turpis maximus fermentum et a magna. Quisque quis lectus justo. Phasellus tempus nulla ac sagittis blandit. Nulla nec gravida dolor.

Duis est neque, placerat eget ipsum a, facilisis dictum nulla. Fusce ut justo porta erat posuere hendrerit. Praesent placerat mi eu ligula tincidunt, sit amet mollis dui tristique. Praesent in egestas felis, sit amet tempus mauris. In malesuada id tortor ut rhoncus. Sed pretium, nibh ut condimentum malesuada, ligula mi hendrerit ligula, id blandit sem urna sit amet ligula. Nullam rutrum cursus laoreet. Etiam a augue non felis maximus aliquet. Etiam ultrices nibh arcu, pellentesque iaculis nisl ultrices vel.

Fusce lacinia non est at porttitor. Cras blandit magna nec quam auctor finibus in ac augue. Curabitur ullamcorper elementum lorem vitae pretium. Vestibulum venenatis metus non ante sagittis, eu porta urna scelerisque. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus sapien lacus, pulvinar non tortor at, mollis vulputate lacus. Mauris finibus dolor et ante semper, id semper tellus dictum. Sed eget risus id nisi commodo malesuada. Integer tellus augue, sollicitudin tincidunt felis dapibus, pulvinar sodales neque. Nunc iaculis nibh a risus ullamcorper egestas. Ut quis nunc at ante bibendum placerat. Mauris in leo feugiat ex scelerisque condimentum. Vivamus in elementum risus. Donec gravida sollicitudin arcu, sed fringilla nibh tempus id. Quisque nec pulvinar magna.

Integer nec condimentum massa. Maecenas vitae dolor maximus, posuere mi id, suscipit odio. Pellentesque neque orci, lacinia at neque in, tincidunt semper nisi. In euismod purus in augue vestibulum, accumsan consectetur leo porta. Proin mauris eros, eleifend vitae egestas eget, cursus ac tellus. Phasellus mollis tellus in varius tincidunt. Ut venenatis consequat consequat. Aenean eu pretium urna. Suspendisse non orci consequat, efficitur justo non, placerat leo. Ut nec dolor commodo, scelerisque urna nec, convallis orci. Cras semper nunc lectus, sit amet volutpat nisl feugiat eu. Cras consequat rhoncus ante non mollis. Nam malesuada ullamcorper rhoncus.

Nullam lobortis lectus id nunc tincidunt, et pretium erat pharetra. Phasellus pellentesque euismod metus, ac placerat lectus pretium lacinia. Phasellus imperdiet dictum augue et vestibulum. Maecenas volutpat, metus et porta tempus, nisl libero tincidunt nisl, a tincidunt magna est et est. Etiam cursus felis vitae congue egestas. Phasellus tincidunt quis lacus vitae iaculis. Fusce quis sem viverra, porttitor eros eu, iaculis risus. Sed quis ornare neque. Morbi pulvinar augue sit amet dapibus vehicula. Cras molestie, nunc in maximus euismod, dui risus mollis arcu, vitae dignissim ante erat et est. Fusce ornare nisl orci, vitae viverra orci ornare eget. Duis risus eros, accumsan vitae leo nec, tempus suscipit tortor. Praesent pretium iaculis ex, ut porta lectus lacinia a. Vestibulum sed augue sit amet nulla rhoncus varius lacinia nec ante. Donec et vestibulum est. In facilisis ultrices dictum. Nulla blandit rutrum. LOL`;
